// layout.tsx
import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '../components/Header'; // Ajusta la ruta según la estructura de tu proyecto
import Sidebar from '../components/Sidebar'; // Ajusta la ruta según la estructura de tu proyecto
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <Header />
      <Sidebar />
      <main className="content">{children}</main>
    </div>
  );
}
